### ISSUE TITLE
For 4th scripts (Nikita):

### ISSUE THREAD

**Issue by yukunzGIT** [UBC-MDS/newyork_restaurant_grading#17]
Here are the codes you need from old script 2:

# split X and y
X_train = train_df.drop(columns=["grade"])
y_train = train_df["grade"]

X_test = test_df.drop(columns=["grade"])
y_test = test_df["grade"]

# features
target = ['grade']
categorical_features = ['boro', 'zipcode', 'cuisine_description', 'action', 'violation_code', 'violation_description', 'critical_flag']
passthrough_features = ['score']
drop_features = ['camis', 'dba', 'inspection_date', 'inspection_type']
text_features = 'violation_description' 

# column transformer
preprocessor = make_column_transformer( 
    ("passthrough", passthrough_features),  
    (OneHotEncoder(handle_unknown="ignore", sparse=False), categorical_features),  
    (CountVectorizer(max_features=2000, stop_words="english"), text_features),
    ("drop", drop_features)
)

preprocessor.verbose_feature_names_out = False

# if you want to see your X_train encoded data frame, use these:
X_train_enc = pd.DataFrame(preprocessor.fit_transform(X_train).toarray(), index=X_train.index, columns=preprocessor.get_feature_names_out())
X_train_enc

**Comment by lzung** [comment]
See here also: https://github.com/UBC-MDS/newyork_restaurant_grading/issues/13
