### ISSUE TITLE
Feature list for Nikita

### ISSUE THREAD

**Issue by yukunzGIT** [UBC-MDS/newyork_restaurant_grading#21]
# Given our large data size, when we remove all the NAs values, we still have a fairly large data size over 150,000. 
# Since we only have one numeric column and it does not make too much sense to replace the NAs with the most frequent class for categorical features (actions might be seen as making up data given lots of existing NAs values), it is better just to drop all the NAs in advance. 

# We combine Grade B/C as Grade F to reduce the problem of class imbalance for the target grading.

# We drop the camis unique identifier since it is just a code assigned to each restaurant and is not helpful for our prediction.

# We would drop the 'dba' since we expect the words in name feature of the restaurants to be unrealted to the grading.

# We would use OHE on 'boro' feature of the restaurant regions.

# Since there are so many restaurants with the same zipcodes, we would OHE it (with appropriate values for min_frequency or max_categories to select the most frequent 20)

# Since the count the 'Other' cuisine type in 'cuisine_description' is 598, we would OHE it (with appropriate values for min_frequency or max_categories to select the most frequent half)

# We would assume that the date of the inspection is unrealted to how restaurants are graded, so we drop the 'inspection_date' feature.

# We would use OHE on 'action' feature.

# We would use OHE on 'violation_code' feature.

# We would use Bag of words on 'violation_description' feature.

# We would use OHE on 'critical_flag' feature.

# Since 'score' is the ONLY numeric feature, We would not apply any transformation on it (no need to do scaling).

# We would drop the 'inspection_type' feature since we expect it does not relate to the grading target.

**Comment by nik11susan** [comment]
Thanks Edward! I will incorporate this
