### ISSUE TITLE
License for the Dataset

### ISSUE THREAD

**Issue by nik11susan** [UBC-MDS/newyork_restaurant_grading#4]
Hi Team,

Just wanted to confirm the license for our dataset from tidytuesday : https://github.com/rfordatascience/tidytuesday/blob/master/LICENSE is the following:
Creative Commons Zero v1.0 Universal

Please let me know if anything changes.

Thanks!

**Comment by lzung** [comment]
I think that should be the right license as well!

**Comment by nik11susan** [comment]
Great!
